### ISSUE TITLE
stop service on kali linux 

### ISSUE THREAD

**Issue by mohsen-abbaspour** [dradis/dradisguides#9]
when run ./start.sh  command  after some second  this error occur
Exiting
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.1.9/lib/active_support/inflector/methods.rb:238:in `const_get': uninitialized constant ProjectScopedController (NameError)

**Comment by rachkor** [comment]
@mohsen-abbaspour what version of Dradis are you running? The latest version of Dradis (v3.1.0.rc2) uses Ruby v2.2.2. Please try installing the latest version of Dradis using these instructions and let us know how it goes! http://dradisframework.org/documentation/install_kali.html

**Comment by mohsen-abbaspour** [comment]
@rachkor 
so tnx   dear friend 

i     pass   installation steps       but when  i   connect  local:3000      this error  displsy on  page site : 

ActiveRecord::PendingMigrationError
 Migrations are pending. To resolve this issue, run: bin/rake db:migrate RAILS_ENV=development
Extracted source (around line #392):

      def check_pending!(connection = Base.connection)
        raise ActiveRecord::PendingMigrationError if ActiveRecord::Migrator.needs_migration?(connection)
      end

      def load_schema_if_pending!

**Comment by mohsen-abbaspour** [comment]
i run   rake   from   dradis-ce/bin     but    this  problem exist ::

/var/lib/gems/2.1.0/gems/factory_girl-4.5.0/lib/factory_girl/linter.rb:14:in `lint!': The following factories are invalid: (FactoryGirl::InvalidFactoryError)

* activity - Could not find table 'activities' (ActiveRecord::StatementInvalid)
* update_activity - Could not find table 'activities' (ActiveRecord::StatementInvalid)
* delete_activity - Could not find table 'activities' (ActiveRecord::StatementInvalid)
* category - Could not find table 'categories' (ActiveRecord::StatementInvalid)
* configuration - Could not find table 'configurations' (ActiveRecord::StatementInvalid)
* evidence - Could not find table 'evidence' (ActiveRecord::StatementInvalid)
* issue - Could not find table 'notes' (ActiveRecord::StatementInvalid)
* node - Could not find table 'nodes' (ActiveRecord::StatementInvalid)
* note - Could not find table 'notes' (ActiveRecord::StatementInvalid)
* tag - Could not find table 'tags' (ActiveRecord::StatementInvalid)

**Comment by rachkor** [comment]
@mohsen-abbaspour were you able to successfully run the `./bin/setup` command from #4 in the instructions? http://dradisframework.org/documentation/install_git.html
Make sure you're running the command from the `dradis-ce/` folder instead of the `dradis-ce/bin` folder. 

If you still get this error after running the `./bin/setup` command, please try running: 
`$ bin/rake db:migrate RAILS_ENV=development` 
From the `dradis-ce/` folder.

**Comment by mohsen-abbaspour** [comment]
@rachkor     so   tnx    my problem solved 

but   is there  CLI ability    to use  Dradis  ??  for example   i want  to  take  xml file in  cli  and  generate report

**Comment by rachkor** [comment]
@mohsen-abbaspour thanks for the update, that's great to hear. 

 Yes, you can use the command line interface to upload or export. Check out the available list of Thor tasks by running: 
`bundle exec thor -T`
from the `dradis-ce` folder. 

I'm going to go ahead and close this thread now that we've resolved the installation problem for you. If you have any other questions, can you create a new thread in our community forums here? http://discuss.dradisframework.org/

**Comment by mohsen-abbaspour** [comment]
@rachkor    so   tnx   

is there problem  to parsing   xml output of  openvas    ??
thor version is  Thor 0.19.1  

i think to  ask this question in another task

**Comment by rachkor** [comment]
@mohsen-abbaspour you may need to enable the OpenVAS add-on first. See details here and let me know on the forums if you have questions: http://discuss.dradisframework.org/t/kali-2-0-distribution-missing-import-plug-ins/326/2?u=rachkor

**Comment by mohsen-abbaspour** [comment]
@rachkor      the  add-on  is installed on my system   when  run  this command : 
"bundle exec thor dradis:plugins:openvas:upload  /home/192.168.1.1.xml"

i get this error 
FATAL -- : No report results were detected in the uploaded file (/report). Ensure you uploaded an OpenVAS XML report.

i am sure that my file is output of openvas 
 if  i wrong (  that isnt :):):)  )  , close this task  and  redirect  me to  relative  link  
so tnx

**Comment by rachkor** [comment]
@mohsen-abbaspour that looks like a file-specific error. Can you check to see that the format of your XML file matches our sample file? https://github.com/dradis/dradis-openvas/blob/1c863eeeb6753b49a28860cfe643d533bd97353d/spec/fixtures/files/v7/report_v7.xml It looks like you may be missing a `<report>` tag. We're already far off the topic of this thead so I am going to lock this conversation. Please post questions here so that others can easily find the answers: http://discuss.dradisframework.org/
